<?xml version="1.0"?>	
<!DOCTYPE stock[	
<!ELEMENT stock (new-car|used-car)*>	
<!ELEMENT new-car (model,price)>	
<!ELEMENT used-car (model,price,mileage,	condition?)>	
<!ELEMENT model (#PCDATA)>	
<!ELEMENT price (#PCDATA)>	
<!ELEMENT mileage (#PCDATA)>	
<!ELEMENT condition (#PCDATA)>	
]>

<stock>
    <new-car>
        <model>D</model>
        <price>20000</price>
    </new-car>
    <used-car>
        <model>rar</model>
        <price>1000</price>
        <mileage>1000000</mileage>
        <condition>Nais</condition>
    </used-car>
</stock>
