<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookDatabase [
    <!ELEMENT bookDatabase (book+)>
    <!ELEMENT book (author+,content+,image?,newchapters?)>
    <!ATTLIST book book ID NMTOKEN #REQUIRED>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT content (chapter,description)>
    <!ELEMENT chapter (#PCDATA)>
    <!ATTLIST chapter number NMTOKEN #REQUIRED>
    <!ELEMENT description (section*,summary?)>
    <!ELEMENT section (#PCDATA)>
    <!ELEMENT summary (#PCDATA)>
    <!ELEMENT image (#PCDATA)>
    <!ELEMENT newchapters (chapter,description)>

    <!ENTITY % multipleAuthors SYSTEM "author+">
    <!ENTITY % optionalImg SYSTEM "image?">
    <!ENTITY % optionalNewChapter SYSTEM "newchapters?">
    
]>
<bookDatabase>
    <book bookID="ISBN-0-13-xxx">
        &multipleAuthors;
        <author>Elliotte Rusty Harold</author>
        <content>
            <chapter number="1">XML Structure, Syntax</chapter>
            <description>
                <section>XML Fundamentals</section>
            </description>
        </content>
        <content>
            <chapter number="2">Document Type Definitions</chapter>
            <description>
                <section>Element Declarations</section>
                <section>Attributes Declarations</section>
                <summary>summary of the chapter 2</summary>
            </description>
        </content>
        &optionalImg;
    </book>
    <book bookID="ISBN-0-586-xxx">
        &multipleAuthors;
        &optionalImg;
        <author>Ian Foster</author>
        <author>Carl Kesselman</author>
        <image>grid architecture</image>
        <content>
            <chapter number="1">Grids in Context</chapter>
            <description/>
        </content>
        <newchapters>
            <chapter number="20">Network structure</chapter>
            <description>
                <section>The Future(1998-2005)</section>
            </description>
        </newchapters>
        &optionalNewChapter;
    </book>
</bookDatabase>
