<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE folks [
    <!ELEMENT folks (person+)>
    <!ELEMENT person (name)>
    <!ATTLIST person pin ID NMTOKEN #REQUIRED>
    <!ATTLIST person friend IDREF NMTOKEN #IMPLIED>
    <!ATTLIST person likes IDREFS CDATA #IMPLIED>
    <!ELEMENT name (#PCDATA)>
]>
<folks>
    <person pin="p1">
        <name>Paula</name>
    </person>
    <person pin="p2" friend="p1">
        <name>Gonzalo</name>
    </person>
        <person pin="p3" likes="p2 p1">
        <name>Catuxa</name>
    </person>
</folks>
