=== nico-a23/VisualStudio_repo/UD4/tractors.dtd
<!ELEMENT order (tractor+)>
<!ELEMENT tractor (component+)>
<!ELEMENT component (manufacturer, delivery_date?, fragile?, weight, serial_number, max_km?)>
<!ATTLIST component fragile (yes|no) #REQUIRED>
<!ATTLIST component weight_unit (kilos|grams) #REQUIRED>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT delivery_date EMPTY>
<!ATTLIST delivery_date day CDATA #IMPLIED>
<!ATTLIST delivery_date month CDATA #REQUIRED>    
<!ATTLIST delivery_date year CDATA #REQUIRED>    
<!ELEMENT fragile (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT serial_number (#PCDATA)>
<!ELEMENT max_km (#PCDATA)>

=== nico-a23/VisualStudio_repo/UD4/Exercise15.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE order SYSTEM "tractors.dtd">
<order>
    <tractor>
        <component fragile="yes" weight_unit="kilos">
            <manufacturer>ABC Tractor Parts</manufacturer>
            <delivery_date day="20" month="02" year="2024"/>
            <weight>100</weight>
            <serial_number>12345</serial_number>
            <max_km>5000</max_km>
        </component>
        <component fragile="no" weight_unit="grams">
            <manufacturer>XYZ Manufacturing</manufacturer>
            <weight>5000</weight>
            <serial_number>54321</serial_number>
        </component>
    </tractor>
</order>
