=== nico-a23/VisualStudio_repo/ejercicios/Exercise16.dtd
<!ELEMENT student_list (student+)>
<!ELEMENT student (name,study_programme,course?)>
<!ATTLIST student matriculation_number NMTOKEN #REQUIRED>
<!ELEMENT name (first_name,middle_name?,last_name)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT study_programme EMPTY>
<!ATTLIST study_programme name CDATA #REQUIRED>
<!ELEMENT course (title,mark_course,exam_mark)>
<!ATTLIST course year NMTOKEN #REQUIRED>
<!ATTLIST course type NMTOKEN #REQUIRED>
<!ATTLIST course recieved_mark NMTOKEN #REQUIRED>
<!ATTLIST course taken_exam NMTOKEN #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT mark_course (#PCDATA)>
<!ELEMENT exam_mark (#PCDATA)>

=== nico-a23/VisualStudio_repo/ejercicios/Exercise16.xml
<!DOCTYPE student_list SYSTEM "Exercise16.dtd">
<student_list>
    <student matriculation_number="111">
        <name>
            <first_name>asdafsfa</first_name>
            <middle_name>sfasfasfa</middle_name>
            <last_name>fsafsafasf</last_name>
        </name>
        <study_programme name="BSc in CS and Engineering"/>
        <course  year="2024" type="undergraduate" recieved_mark="yes" taken_exam="yes">
            <title>safasfasf</title>
            <mark_course>9</mark_course>
            <exam_mark>10</exam_mark>
        </course>
            
    </student>
    <student matriculation_number="112">
        <name>
            <first_name>asfasgsf</first_name>
            <last_name>asgagreaefsfas</last_name>
        </name>
        <study_programme name="BSc in Applied CS"/>
        
    </student>
</student_list>
