<!DOCTYPE hogwarts [
    <!ELEMENT hogwarts (rooms, teachers, courses)>
    <!ELEMENT rooms (room+)>
    <!ELEMENT room EMPTY>
    <!ATTLIST room name NMTOKEN #REQUIRED>
    <!ATTLIST room nrSeats NMTOKEN #REQUIRED>
    <!ELEMENT teachers (teacher+)>
    <!ELEMENT teacher (title?)>
    <!ATTLIST teacher name NMTOKEN #REQUIRED>
    <!ATTLIST teacher room NMTOKEN #REQUIRED>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT courses (course+)>
    <!ELEMENT course (class+)>
    <!ATTLIST course name NMTOKEN #REQUIRED>
    <!ATTLIST course teacher NMTOKEN #REQUIRED>
    <!ATTLIST course nrStudents NMTOKEN #IMPLIED>
    <!ELEMENT class (#PCDATA)>
    <!ATTLIST class day NMTOKEN #REQUIRED>
    <!ATTLIST class hour NMTOKEN #REQUIRED>

]>
<hogwarts>
    <rooms>
        <room name="The_Dungeon" nrSeats="34"/>
        <room name="The_Cabin" nrSeats="163"/>
    </rooms>
    <teachers>
        <teacher name="Snape" room="The_Dungeon">
            <title>Professor</title>
        </teacher>
        <teacher name="Hagrid" room="The_Cabin"/>
    </teachers>
    <courses>
        <course name="Potioncraft" teacher="Snape" nrStudents="28">
            <class day="Monday" hour="10"/>
        </course>
        <course name="Handling_of_Wild_Creatures" teacher="Hagrid">
            <class day="Saturday" hour="13"/>
            <class day="Thursday" hour="7"/>
        </course>
    </courses>
</hogwarts>