=== nico-a23/VisualStudio_repo/ejercicios/tractors.dtd
<!ELEMENT order (tractor+)>
<!ELEMENT tractor (component+)>
<!ELEMENT component (manufactors_name,delivery_date,weight)>
<!ATTLIST component fragile NMTOKEN #REQUIRED>
<!ELEMENT manufactors_name (#PCDATA)>
<!ELEMENT delivery_date EMPTY>
<!ATTLIST delivery_date day NMTOKEN #IMPLIED>
<!ATTLIST delivery_date month NMTOKEN #REQUIRED>
<!ATTLIST delivery_date year NMTOKEN #REQUIRED>
<!ELEMENT weight (serial_number,maximum_km?)>
<!ATTLIST weight unit NMTOKEN #REQUIRED>
<!ELEMENT serial_number (#PCDATA)>
<!ELEMENT maximum_km (#PCDATA)>

=== nico-a23/VisualStudio_repo/ejercicios/tractors.xml
<!DOCTYPE order SYSTEM "tractors.dtd">
<order>
    <tractor>
        <component fragile="yes">
            <manufactors_name>safasfas</manufactors_name>
            <delivery_date day="12" month="10" year="2024"/>
            <weight unit="kilos">
                <serial_number>14243</serial_number>
                <maximum_km>100</maximum_km>
            </weight>
            
        </component>
        <component fragile="no">
            <manufactors_name>sdafasasd</manufactors_name>
            <delivery_date day="12" month="10" year="2024"/>
            <weight unit="kilos">
                <serial_number>12323</serial_number>
            </weight>
        </component>
    </tractor>
    <tractor>
        <component fragile="no">
            <manufactors_name>sfasfasf</manufactors_name>
            <delivery_date month="10" year="2024"/>
            <weight unit="grams">
                <serial_number>12423</serial_number>
                <maximum_km>100</maximum_km>
            </weight>
        </component>
    </tractor>
</order>
