=== nico-a23/VisualStudio_repo/UD4 2º PARTE/prescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="prescription">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="physician">
                    <xs:complexType  mixed="true">
                        
                        <xs:attributeGroup name="patientGroup">
                            <xs:attribute name="prescriptionID"use="required"/>
                            <xs:attribute name="physicianName" use="required" />
                            <xs:attribute name="patientID" type="xs:integer" use="required" />
                        </xs:attributeGroup>
                        <xs:group name="physicianGroup">
                            <xs:sequence>
                                <xs:element name="physicianName" type="xs:string"/>
                                <xs:element name="organization" type="xs:string"/>
                            </xs:sequence>
                        </xs:group>    
                       
                        <xs:attribute name="physicianID" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="date" type="xs:string" />
                <xs:element name="brandName" type="xs:string" />
                <xs:element name="strength"/>
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:integer">
                                <xs:attribute name="units" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                <xs:element name="packageSize" type="xs:string" />
                <xs:element name="dosageInstruction" type="xs:string" />
                <xs:element name="use" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="prescriptionID" use="required" />
            <xs:attribute name="patienName" use="required" />
            <xs:attribute name="patientID" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nico-a23/VisualStudio_repo/UD4 2º PARTE/prescription.xml
<prescription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="prescription.xsd" prescriptionID="pr12345" patienName="Carmen Rubio"
    patientID="121212">
    <physician physicianID="232323">
        Important information
        <physicianName>Hugo LÃ¡ncara</physicianName>
        <organization> University Hospital </organization>
    </physician>
    <date>2022-09-12</date>
    <brandName> Diovan </brandName>
    <strength units="mg"> 5 </strength>
    <packageSize> 20 </packageSize>
    <dosageInstruction>One tablet a day </dosageInstruction>
    <use> For high blood pressure </use>
</prescription>
