=== nico-a23/VisualStudio_repo/UD4 2º PARTE/youtube.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="youtube">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="videos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="video" type="videoType">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="url" type="xs:string" />
                                        <xs:element name="views" type="xs:string" />
                                        <xs:element name="comments">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="good" type="xs:string" />
                                                    <xs:element name="bad" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="subscribers" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="subscriber">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="subscriptionDate">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="day"
                                                                            type="xs:integer"
                                                                            use="required" />
                                                                        <xs:attribute name="month"
                                                                            use="required" />
                                                                        <xs:attribute name="year"
                                                                            type="xs:integer"
                                                                            use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="comments">
                                                                    <xs:complexType>
                                                                        <xs:attribute
                                                                            name="quantity"
                                                                            type="xs:integer"
                                                                            use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="email">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="user"
                                                                                type="xs:string" />
                                                                            <xs:element
                                                                                name="server">
                                                                                <xs:complexType>
                                                                                    <xs:choice>
                                                                                        <xs:element
                                                                                            name="gmail" />
                                                                                        <xs:element name="hotmail"/>
                                                                                        <xs:element name="iessanclemente.net"/>
                                                                                    </xs:choice>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute
                                                                            name="completo"
                                                                            use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="language"
                                                                    type="availableLanguages" />
                                                            </xs:sequence>
                                                            <xs:attribute name="code" type="subscriberCodeType" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="advertisement">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ad">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="company" type="xs:string" />
                                        <xs:element name="bannersPerMinute" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sponsoredAd">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="company" type="xs:string" />
                                        <xs:element name="bannersPerMinute" type="xs:string" />
                                        <xs:element name="youTubeDiscount" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="sponsor" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="availableLanguages" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="videoType" mixed="true">
        <xs:sequence>
            <xs:element name="url" type="xs:anyURI"/>
            <xs:element name="views" type="viewsType"/>
            <xs:element name="comments" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="good" type="goodViewsType"/>
                        <xs:element name="bad" type="xs:integer"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="subscribers" minOccurs="0"/>
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="subscriber" type="subscriberType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="availableLanguages">
        <xs:restriction base="xs:string">
            <xs:enumeration value="French"/>
            <xs:enumeration value="Italian"/>
            <xs:enumeration value="German"/>
            <xs:enumeration value="English"/>
            <xs:enumeration value="Chinese"/>
            <xs:enumeration value="Korean"/>
            <xs:enumeration value="Japanese"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="viewsType">
        <xs:restriction>
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="200000"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="subscriberCodeType">
        <xs:restriction>
            <xs:pattern value="\d{2}-\[[A-Z]{2}\]-\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== nico-a23/VisualStudio_repo/UD4 2º PARTE/youtube.xml
<?xml version="1.0" encoding="UTF-8"?>
<youtube xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="youtube.xsd">
	<videos>
		<video>XSD Overview
			<url>https://www.youtube.com/watch?v=PpvX3izvRWU</url>
			<views>112000</views>
			<comments>
				<good>1200</good>
				<bad>700</bad>
			</comments>
			<subscribers>
				<subscriber code="15-[AR]-56">
					<subscriptionDate day="12" month="february" year="2023"/>
					<comments quantity="12"/>
					<email completo="rafa@gmail.com">
						<user>rafa</user>
						<server><gmail/></server>
                    </email>
					<language>Korean</language>
				</subscriber>
			</subscribers>
		</video>
	</videos>
	<advertisement>
		<ad>
			<company>Seresco</company>
			<bannersPerMinute>40000</bannersPerMinute>
		</ad>
		<sponsoredAd sponsor="Google">
			<company>Gadis</company>
			<bannersPerMinute>15000</bannersPerMinute>
			<youTubeDiscount>23%</youTubeDiscount>
        </sponsoredAd>
	</advertisement>
	<availableLanguages>French Italian German English Chinese Korean Japanese</availableLanguages>
</youtube>
